name: Terraform CI/CD for terraform-infra

on:
  push:
    branches:
      - terraform-infra

jobs:
  terraform:
    name: Apply Terraform Changes
    runs-on: ubuntu-latest

    steps:
      # 1. GitHub ì €ì¥ì†Œì—ì„œ ì½”ë“œ ì²´í¬ì•„ì›ƒ
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Terraform ì„¤ì¹˜
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0

      # 3. Terraform ì´ˆê¸°í™” (Init)
      - name: Terraform Init
        run: cd terraform && terraform init
    
      - name: Terraform Plan
        run: cd terraform && terraform plan
    
      - name: Terraform Apply
        run: cd terraform && terraform apply -auto-approve

      # 6. Slack ì•Œë¦¼ (ì„ íƒ ì‚¬í•­)
      # - name: Notify Slack
      #   uses: rtCamp/action-slack-notify@v2
      #   env:
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      #   with:
      #     args: "Terraform Apply ì™„ë£Œ ğŸš€"